name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Snake com tema claro
      - name: Gerar Snake - Claro
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      # Snake com tema escuro (pretos)
      - name: Gerar Snake - Escuro (preto)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake-dark.svg
          palette: "[#0a0a0a,#1a1a1a,#2a2a2a,#3a3a3a,#4a4a4a]"

      # Publica na branch `output`
      - name: Publicar SVG na branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
